version: '3.9'

services:
  postgres:
    image: postgres:latest # TODO: substituir o latest pela versao do POSTGRES utilizada no servidor de PRD
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=
      - POSTGRES_PASSWORD=
      - POSTGRES_USER=
