export enum ServiceTypes {
  TECHNOLOGY = 'Tecnologia',
  MECHANICS = 'Mecânica',
  HEALTHCARE = 'Saúde',
  EDUCATION = 'Educação',
  CONSTRUCTION = 'Construção',
  ART = 'Arte',
  FINANCE = 'Finanças',
  TRANSPORT = 'Transporte',
  RETAIL = 'Varejo',
  AGRICULTURE = 'Agricultura',
  AUTOMOTIVE = 'Automobilística',
  CONSULTING = 'Consultoria',
  ENERGY = 'Manutenção',
  ENTERTAINMENT = 'Entretenimento',
  FOOD_SERVICE = 'Serviço de Alimentos',
  UTILITIES = 'Utilidades',
  LEGAL = 'Jurídico',
  REAL_ESTATE = 'Imobiliário',
  SOCIAL_SERVICES = 'Serviços Sociais',
  TELECOMMUNICATIONS = 'Telecomunicações',
}
