name: Check

on: pull_request

jobs:
  check:
    if: startsWith(github.head_ref, 'dependabot/') == false
    name: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: yarn install

      - name: TypeScript Check
        run: tsc

      - name: Lint Check
        run: yarn lint:check
